In [38]:
import pandas as pd
import numpy as np
df =pd.read_csv("diabetes_unclean.csv")

In [39]:
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          1
Urea         1
Cr           2
HbA1c        3
Chol         2
TG           2
HDL          1
LDL          2
VLDL         1
BMI          0
CLASS        0
dtype: int64

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009 entries, 0 to 1008
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1009 non-null   int64
 1   No_Pation  1009 non-null   int64
 2   Gender     1009 non-null   object
 3   AGE        1008 non-null   float64
 4   Urea       1008 non-null   float64
 5   Cr         1007 non-null   float64
 6   HbA1c      1006 non-null   float64
 7   Chol       1007 non-null   float64
 8   TG         1007 non-null   float64
 9   HDL        1008 non-null   float64
 10  LDL        1007 non-null   float64
 11  VLDL       1008 non-null   float64
 12  BMI        1009 non-null   float64
 13  CLASS      1009 non-null   object
dtypes: float64(10), int64(2), object(2)
memory usage: 110.5+ KB

In [41]:
df= df.fillna(df.mean(numeric_only=True))
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
1,735,34221,M,26.0,4.500000,62.0,4.900000,3.7,1.4,1.1,2.1,0.600000,23.0,N
2,420,47975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
3,680,87656,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
4,504,34223,M,33.0,7.100000,46.0,4.900000,4.9,1.0,0.8,2.0,0.400000,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,191,454316,M,55.0,5.131094,62.0,6.800000,5.3,2.0,1.0,3.5,0.900000,30.1,Y
1005,192,454316,M,55.0,4.800000,88.0,8.284155,5.7,4.0,0.9,3.3,1.800000,30.0,Y
1006,193,454316,M,62.0,6.300000,82.0,6.700000,5.3,2.0,1.0,3.5,1.850595,30.1,Y
1007,194,454316,F,57.0,4.100000,70.0,9.300000,5.3,3.3,1.0,1.4,1.300000,29.0,Y
1008,195,4543,f,55.0,4.100000,34.0,13.900000,5.4,1.6,1.6,3.1,0.700000,33.0,Y

In [42]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1004    False
1005    False
1006    False
1007    False
1008    False
Length: 1009, dtype: bool

In [43]:
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [44]:
df["Gender"].count()

np.int64(1009)

In [45]:
df["Gender"].value_counts()

Gender
M    570
F    437
f      2
Name: count, dtype: int64

In [46]:
df["Gender"]=df["Gender"].replace("f","F")

In [47]:
df["Gender"].value_counts()

Gender
M    570
F    439
Name: count, dtype: int64

In [49]:
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
1,735,34221,M,26.0,4.500000,62.0,4.900000,3.7,1.4,1.1,2.1,0.600000,23.0,N
2,420,47975,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
3,680,87656,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0,N
4,504,34223,M,33.0,7.100000,46.0,4.900000,4.9,1.0,0.8,2.0,0.400000,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,191,454316,M,55.0,5.131094,62.0,6.800000,5.3,2.0,1.0,3.5,0.900000,30.1,Y
1005,192,454316,M,55.0,4.800000,88.0,8.284155,5.7,4.0,0.9,3.3,1.800000,30.0,Y
1006,193,454316,M,62.0,6.300000,82.0,6.700000,5.3,2.0,1.0,3.5,1.850595,30.1,Y
1007,194,454316,F,57.0,4.100000,70.0,9.300000,5.3,3.3,1.0,1.4,1.300000,29.0,Y
1008,195,4543,F,55.0,4.100000,34.0,13.900000,5.4,1.6,1.6,3.1,0.700000,33.0,Y

# import library

In [48]:
from sklearn.model_selection import train_test_split

In [51]:
y=df["CLASS"]
y.shape

(1009,)

In [52]:
y=df[["CLASS"]]
y.shape

(1009, 1)

In [53]:
y

     CLASS
0        N
1        N
2        N
3        N
4        N
...    ...
1004    Y
1005    Y
1006    Y
1007    Y
1008    Y

[1009 rows x 1 columns]

In [54]:
x=df.drop(["ID","No_Pation","CLASS"],axis=1)
x

,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
0,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0
1,M,26.0,4.500000,62.0,4.900000,3.7,1.4,1.1,2.1,0.600000,23.0
2,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0
3,F,50.0,4.700000,46.0,4.900000,4.2,0.9,2.4,1.4,0.500000,24.0
4,M,33.0,7.100000,46.0,4.900000,4.9,1.0,0.8,2.0,0.400000,21.0
...,...,...,...,...,...,...,...,...,...,...,...
1004,M,55.0,5.131094,62.0,6.800000,5.3,2.0,1.0,3.5,0.900000,30.1
1005,M,55.0,4.800000,88.0,8.284155,5.7,4.0,0.9,3.3,1.800000,30.0
1006,M,62.0,6.300000,82.0,6.700000,5.3,2.0,1.0,3.5,1.850595,30.1
1007,F,57.0,4.100000,70.0,9.300000,5.3,3.3,1.0,1.4,1.300000,29.0
1008,F,55.0,4.100000,34.0,13.900000,5.4,1.6,1.6,3.1,0.700000,33.0

In [60]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [63]:
x_train.shape

(756, 11)

In [67]:
x_test.shape

(253, 11)

In [64]:
y_train.shape

(756, 1)

In [68]:
y_test.shape

(253, 1)

# test_size   and random_state

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [86]:
y_test

    CLASS
566     Y
493     Y
875     Y
849     Y
432     Y
..    ...
883     Y
801     Y
45      N
373     Y
495     Y

[505 rows x 1 columns]

In [87]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [89]:
y_test

    CLASS
891     Y
753     Y
452     Y
667     Y
353     Y
..    ...
31      N
315     Y
193     Y
384     Y
307     Y

[202 rows x 1 columns]

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=10)

In [90]:
y_test

    CLASS
891     Y
753     Y
452     Y
667     Y
353     Y
..    ...
31      N
315     Y
193     Y
384     Y
307     Y

[202 rows x 1 columns]